name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
      - name: Login to Docker Hub
        uses: docker/login-action@v1.0.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.0.0
      - name: Build and push
        uses: docker/build-push-action@v3.0.0
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/pvt:profile_webpage:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/pvt:profile_webpage:v1.0.0
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/profile_webpage:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/profile_webpage:buildcache,mode=max
