name: Docker Profile Webpage Image CI & CD

on:
  push:
    branches:
      - master
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE
  pull_request:
    branches:
      - master
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - name: Setup bashrc
        run: |
          echo '# Install Ruby Gems to ~/gems' >> ~/.bashrc
          echo 'export GEM_HOME="$HOME/gems"' >> ~/.bashrc
          echo 'export PATH="$HOME/gems/bin:$PATH"' >> ~/.bashrc
          source ~/.bashrc
      - name: Setup install bundler
        run: gem install jekyll bundler
      - name: Setup install bundler dependcy
        run: bundler
      - name: Exec jekyll
        run: JEKYLL_ENV=production bundle exec jekyll b
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/pvt:profile.webpage.latest,${{ secrets.DOCKER_HUB_USERNAME }}/pvt:profile.webpage.v1.0.0
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/pvt:profile.webpage.buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/pvt:profile.webpage.buildcache,mode=max
